minimal_mistakes_skin    : "dirt" # "defautl", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR"          # 블로그 언어
title                    : "111kitty@naver.com"     # 블로그 이름
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "jeongmin"         # 블로그에서 사용될 닉네임
description              : ""      # 블로그 설명: 블로그 링크 공유 시 표시
url                      : "https://jmds07191700.github.io"                                   # 블로그 url
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "https://github.com/jmds07191700/wedding_.github.io"             # Github repo url
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
